### ISSUE TITLE
My complements week 1

### ISSUE THREAD

**Issue by TimTerwijn** [mordock/web-app-from-scratch-1920#1]
Has a gitignore.
No magic numbers (GOOD)
No innerHTML (GOOD)

**Comment by mordock** [comment]
**Maybe you could your descripe your API a bit? Like the url to it and the manual? (FEEDBACK):**
Good points, I'll go and add one the Api objects as example.

**Code is written in test.js (FEEDBACK):**
Yeah, I should probably fix that :)

 **You do 6 fetches in a row, maybe you could make it to one fetch for speed? (FEEDBACK)**
Yes, this will be the first thing I fix during the refactor!

**Comment by mordock** [comment]
Thanks
