### ISSUE TITLE
You still use some vars here and there

### ISSUE THREAD

**Issue by TimTerwijn** [mordock/web-app-from-scratch-1920#14]
Like here:
https://github.com/mordock/web-app-from-scratch-1920/blob/a4a19dc4fabc708331863dad2c8592a165a3fec2/docs/js/app.js#L64-L86

**Comment by TimTerwijn** [comment]
Also, maybe use a foreach?

**Comment by mordock** [comment]
Will fix the vars.
cant use foreach sadly, dont have a list to loop through, this is based on the amount of people I want to show

**Comment by TimTerwijn** [comment]
ahhh, mb

**Comment by mordock** [comment]
fixed vars
