### ISSUE TITLE
Global vars are bad ;)

### ISSUE THREAD

**Issue by TimTerwijn** [mordock/web-app-from-scratch-1920#16]
https://github.com/mordock/web-app-from-scratch-1920/blob/a4a19dc4fabc708331863dad2c8592a165a3fec2/docs/js/app.js#L1-L17

Maybe read:
http://wiki.c2.com/?GlobalVariablesAreBad

**Comment by mordock** [comment]
I know, i'll fix as many as possible, but I need some :)

**Comment by TimTerwijn** [comment]
you can make a class, OR use the function hack Joost showed

**Comment by mordock** [comment]
reduces as much as possible
