### ISSUE TITLE
Assessment week 2

### ISSUE THREAD

**Issue by thijsbordewijk** [mordock/web-app-from-scratch-1920#18]
1. Code is looking good! would be sufficient at the very least!
2. Code still has to be split up in modules.
3. Data is being fetched nicely, sufficient at least.
4. Map, filter and reduce have yet to be added.
5. Rendering is working nicely! sufficient at least.
6. Routie is working nicely, states are not that expansive yet.
7. actor and interaction diagrams look great!
8. loading state present! great feedback! 

:)

**Comment by mordock** [comment]
all this done
