### ISSUE TITLE
Feedback week 1

### ISSUE THREAD

**Issue by charder001** [mordock/web-app-from-scratch-1920#2]
- Readme is missing title, concept, api description
- Maybe look at why you are using vars in combination with const
- Nice error handling
- Nice comments
- Good avoidance of innerHTML
- Some other loop-method might be more efficient
https://github.com/mordock/web-app-from-scratch-1920/blob/4cbc36979e183408aa6f4775e2fbcbf6a434b02a/docs/js/Test.js#L15-L34

**Comment by mordock** [comment]
**Readme is missing title, concept, api description**
Yes I will change it, haven't spend too much time on it.
**Maybe look at why you are using vars in combination with const**
You're right, I'm still used to ES5.
**Nice error handling**
Thanks
**Nice comments**
Thank you, I try to put a lot of focus on this.
**Good avoidance of innerHTML**
Thanks
**Some other loop-method might be more efficient**
Yes, this is on top of my refactor list

**Comment by mordock** [comment]
fixed all
